version: 2
jobs:
  deploy-infra:
    docker:
      - image: hashicorp/terraform:light

    steps:
      - checkout

      - run:
          name: Terraform
          command: |
            cd terraform
            terraform init
            terraform refresh
            terraform apply -auto-approve

      - run:
          name: Commit Build Artifacts
          command: |
            git config --global user.email "${GITHUB_EMAIL}"
            git config --global user.name "${CIRCLE_USERNAME}"
            git commit -am "CircleCI build ${CIRCLE_BUILD_NUM}"

      - persist_to_workspace:
          root: .
          paths:
            - .

  test-build-cljs:
    docker:
      - image: circleci/clojure

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Test
          command: lein test

      - run:
          name: Build
          command: lein do clean, cljsbuild once min

      - run:
          name: Commit Build Artifacts
          command: |
            git config --global user.email "${GITHUB_EMAIL}"
            git config --global user.name "${CIRCLE_USERNAME}"
            git commit -am "CircleCI build ${CIRCLE_BUILD_NUM}"

      - persist_to_workspace:
          root: .
          paths:
            - .


  deploy:
    docker:
      - image: hashicorp/terraform:light

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Install awscli
          command: |
            apk -v --update add python py-pip git-subtree
            pip install --upgrade awscli==1.14.5 s3cmd==2.0.1 python-magic

      - run:
          name: Push to s3
          command: >
            aws s3 cp resources/public/ s3://kerbyferris.com
            --recursive
            --acl public-read

      # - run:
      #     name: Push to github pages
      #     command: |
      #       git config core.sshCommand 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' 
      #       git subtree push --prefix resources/public/ origin gh-pages


workflows:
  version: 2
  deploy-master:
    jobs:
      - deploy-infra:
          filters:
            branches:
              only:
                - master
          context: kerbyferris
      - test-build-cljs:
          requires:
            - deploy-infra
          filters:
            branches:
              only:
                - master
          context: kerbyferris
      - deploy:
          requires:
            - test-build-cljs
          filters:
            branches:
              only:
                - master
          context: kerbyferris
