version: 2
jobs:
  deploy-infra:
    docker:
      - image: hashicorp/terraform:light

    steps:
      - checkout

      - run:
          name: Terraform
          command: |
            cd terraform
            terraform init
            terraform apply -auto-approve

      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy-live:
    docker:
      - image: hashicorp/terraform:light

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Install awscli
          command: |
            apk -v --update add python py-pip 
            pip install --upgrade awscli==1.14.5 s3cmd==2.0.1 python-magic

      - run:
          name: Configure Credentials
          command: |
            aws configure set kerbyferris.aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set kerbyferris.aws_secret_access_key $AWS_SECRET_ACCESS_KEY

      - run:
          name: Push to s3
          command: >
            aws s3 cp live/ s3://kerbyferris.com
            --recursive
            --acl public-read

      - persist_to_workspace:
          root: .
          paths:
            - .

  test-build-cljs:
    docker:
      - image: circleci/clojure

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Test
          command: lein test

      - run:
          name: Build
          command: lein do clean, cljsbuild once min

      - run:
          name: Commit Build Artifacts
          command: git commit -am "CircleCI build: ${CIRCLE_BUILD_NUM}"

      - persist_to_workspace:
          root: .
          paths:
            - .


  deploy-s3:
    docker:
      - image: hashicorp/terraform:light

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Install awscli
          command: |
            apk -v --update add python py-pip git-subtree
            pip install --upgrade awscli==1.14.5 s3cmd==2.0.1 python-magic

      - run:
          name: Push to s3
          command: >
            aws s3 cp resources/public/ s3://cljs.kerbyferris.com
            --recursive
            --acl public-read

      - run:
          name: Push to github pages
          command: |
            git config core.sshCommand 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' 
            git subtree push --prefix resources/public/ origin gh-pages


workflows:
  version: 2
  deploy-live:
    jobs:
      - deploy-infra:
          filters:
            branches:
              only:
                - live
          context: kerbyferris
      - deploy-live:
          requires:
            - deploy-infra
          filters:
            branches:
              only:
                - live
          context: kerbyferris
  deploy-master:
    jobs:
      - deploy-infra:
          filters:
            branches:
              only:
                - master
          context: kerbyferris
      - test-build-cljs:
          requires:
            - deploy-infra
          filters:
            branches:
              only:
                - master
          context: kerbyferris
      - deploy-s3:
          requires:
            - test-build-cljs
          filters:
            branches:
              only:
                - master
          context: kerbyferris
