name: Deploy
on: [push]
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup teraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: 1.1.6

      - name: run tf-init
        id: init
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: env && terraform init
              -backend-config="access_key=$AWS_ACCESS_KEY_ID"
              -backend-config="secret_key=$AWS_SECRET_ACCESS_KEY"

