name: Deploy
on: [push]
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: 1.1.6

      - name: run tf-init
        id: init
        working-directory: ./terraform
        run: terraform init

