name: Deploy
on:
  push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

#      - name: compile production files
#        uses: actions/setup-java@v2
#        with:
#          distribution: 'zulu'
#          java-version: '8'
#      - run: lein do clean, cljsbuild once min

      - uses: chrislennon/action-aws-cli@v1.1
      - run: aws s3 ls
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
