name: Deploy
on: [push]
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: compile production files
        uses: actions/setup-java@v2
        with:
          java-version: '8'
      - run: lein do clean, cljsbuild once min
