name: Deploy
on: [push]
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: compile production files
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - run: lein do clean, cljsbuild once min

      - name: Echo version of aws-cli
        uses: hannut91/aws-cli@1.18.43
        with:
          args: --version
