name: Deploy
on: [push]
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: 1.1.6
        working-directory: ./terraform
        run: terraform init

