name: Deploy
on: [push]
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup teraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: 1.1.6

      - name: run tf-init
        id: init
        working-directory: ./terraform
        run: echo ${{ secrets.SOMETHING}} && terraform init '-backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"'


