name: Deploy
on: [push]
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

#      - name: compile production files
#        uses: actions/setup-java@v2
#        with:
#          distribution: 'zulu'
#          java-version: '8'
#      - run: lein do clean, cljsbuild once min
#
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: try cli
        run: aws s3 ls

#        - name: Echo version of aws-cli
#          uses: hannut91/aws-cli@1.18.43
#          with:
#            args: s3 ls
#          env:
#            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#            AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
#      - name: Upload files
#        uses: hannut91/aws-cli@v1.18.43
#        with:
#          args: s3 cp resources/public/ s3://kerbyferris.com --recursive --acl public-read
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

